swagger: "2.0"
info:
  description: "Sample documentasi cara penggunaan api"
  version: "1.0.0"
  title: "Documentation Api For Backend Web"
  contact:
    email: "andihoerudin24@gmail.com"
host: "127.0.0.1:8080/api/v1"
basePath: "/"
tags:
- name: "Post"
  description: "Everything About Post"
- name: "User"
  description: "Everything About User"
schemes:
- "http"
- "https"
paths:
  /post/all:
    get:
      tags:
      - "Post"
      summary: "Register user store with form data"
      description: ""
      operationId: "register"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      responses:
        "200":
          description: ""
